### ISSUE TITLE
sometimes statusline display nothing

### ISSUE THREAD

**Issue by fcying** [mg979/vim-visual-multi#10]
use test branch.

use `<c-n>` select the word, and then use `]` to find next, if I Always press repeatedly `]`, sometimes statusline will display nothing.
correct:
![image](https://user-images.githubusercontent.com/106934/43038137-b930ac42-8d46-11e8-84c7-9bf077ca4d76.png)

error:
![image](https://user-images.githubusercontent.com/106934/43038143-c8895e50-8d46-11e8-9f2c-cd420432df07.png)

**Comment by mg979** [comment]
This seems more a redrawing issue rather than a bug. It tends to happen when the window border is reached and it is scrolled. I'm never using `:redraw!` because it causes a flash of the screen in vim (not in nvim). If there is a bug, is that sometimes two messages in a row are drawn, an they shouldn't.

So, for now, this won't change. I could force a redraw in neovim, but maybe in the future. Unless you are talking about something different entirely.

**Comment by fcying** [comment]
Is there any way to manually show them? I tried `c-l` but not work.

**Comment by mg979** [comment]
Try pressing `Space` two times? Pressing it only once would disable mappings.

**Comment by fcying** [comment]
it can be work, thanks a lot~~
