### ISSUE TITLE
<CR> adds an extra line with coc.nvim default configuration

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#122]
**Describe the issue:**

```<CR>``` is a **coc.nvim** mapping that select a completion, when in VM insert mode, it does select the completion but adds an extra line.

**Steps to reproduce**  

1. ```<C-n>``` multiple times on a word
2. ```c```
3. start typing, select completion in menu with arrows
4. press Enter

Minimal vimrc:
```vim
call plug#begin('./plugins')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'mg979/vim-visual-multi', {'branch': 'master'}
call plug#end()

inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

-----

- **Operating System**:  Debian Testing
- **Vim Version**:   NVIM v0.5.0-593-g1ca67a73c
Build type: Release
- **commit SHA/branch**:  master

**Comment by mg979** [comment]
See #108, #103 

Basically I'm following vim default behaviour (enter a new line also with popup visible).

You have to do this:

    autocmd User visual_multi_mappings  imap <buffer><expr> <CR> pumvisible() ? "\<C-Y>" : "\<Plug>(VM-I-Return)"

I can't just take whatever command `<CR>` is bound to, because if it's something like `vim-endwise` it would mess things up, it's better if VM doesn't try to do too much in insert mode and sticks with vim defaults, but that autocommand should work.

**Comment by antoinemadec** [comment]
@mg979 , got it.

Would it be possible to use ```maparg()``` (I guess in ```vm#maps#all#buffer()``` instead?
This would allow to keep the user/other plugins mapping and _intercept_ the <CR> as well.

What do you think?

**Comment by antoinemadec** [comment]
As a POC, I changed this in autoload/vm/maps/all.vim line 194:
```vim
        \"I Return":                [maparg('<CR>', 'i'),        'i'],
```

and this fixed my issue.

To be clean, we would need to do something like:
```vim
let cr = maparg('<CR>', 'i')
let cr = empty(cr) ? '<CR>' : cr
" ...
        \"I Return":                [cr,        'i'],
```
but you get the idea.

**Comment by mg979** [comment]
> I changed this in autoload/vm/maps/all.vim line 194

What is your `maparg('<CR>', 'i')`?

If this is safe or not depends on what your `<CR>` does in insert mode. I just tried it and with my `<CR>` insert mode mapping VM errors on start. I don't even know how that would work, though.

As I wrote before

> I can't just take whatever command <CR> is bound to, because if it's something like vim-endwise it would mess things up

The problem is that many plugin commands are dangerous if run on multiple cursors, and especially in insert mode, because only the primary cursor is in insert mode, the others are updated with `setline()`, and commands that modify the buffer in a non-standard way would break the other cursors.

**Comment by antoinemadec** [comment]
@mg979 got it, thanks.
Will try to modify my mappings to make it work in vim-visual-multi.

Thanks for the great plugin, it seems it has matured a lot since I worked on the test environment :smile: 
Might switch to ```vim-visual-multi``` instead of ```vim-multiple-cursors```!

Cheers,
Antoine

**Comment by mg979** [comment]
> since I worked on the test environment 😄

By the way BIG thanks for that, the plugin would have never got far without it, I still run tests before merging stuff into master and they caught a lot of problems.

For coc.nvim:

    autocmd User visual_multi_mappings  imap <buffer><expr> <CR> pumvisible() ? "\<C-Y>" : "\<Plug>(VM-I-Return)"

This works, it was made for this reason, see `:h vm-faq-functions`

**Comment by antoinemadec** [comment]
@mg979 , no problem!

Yes, the <CR> mapping works just fine, but I had other issues with my config.
It was due to a brutal:
```vim
autocmd BufWinLeave * call clearmatches()
```

I removed it, and now it works fine!
