### ISSUE TITLE
gUiw only apply to one cursor

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#124]
**Describe the issue:**

In cursor mode, ```gUiw``` only capitalize current cursor, not the other ones.

**Steps to reproduce**  

1. press ```<C-Down>``` to create 2 cursors
2. press ```gUiw``` to capitalize a word
3. only the _active_ cursor is capitalize

-----

- **Operating System**:  Debian Testing
- **Vim Version**:  NVIM v0.5.0-593-g1ca67a73c
Build type: Release
- **commit SHA/branch**:  master

**Comment by mg979** [comment]
:h vm-cursor-mode

Right now only a subset of vim operators is supported directly, because I have to parse the text object manually (afaik there isn't a variable that holds the last entered text objext, maybe the last operator). For case change, there is built-in support for [vim-abolish](https://github.com/tpope/vim-abolish) that is better than `gU/gu` anyway.

Otherwise you can use a normal command at cursors

    :h visual-multi-run-at-cursors

**Comment by mg979** [comment]
Alternatively you can do this: since `cr` (from `abolish`) is recognized anyway and processed as an operator, you can make these (regular) mappings and they will work:

```vim
" uppercase/lowercase/capitalize
nnoremap crU gUiw
nnoremap cru guiw
nnoremap crC guiw~
```

**Comment by mg979** [comment]
In the test branch (if somebody wants to try it out) I reworked the system, so that `g:VM_user_operators` works for all operators, so you can have any custom operator working in VM.

    :h g:VM_user_operators

It can't be automatic because stuff must be mapped anyway... There is no 'read last motion' function or variable I can use. I thought once about recording a macro but I don't think it would work.

**Comment by antoinemadec** [comment]
@mg979 

run-at-cursor is very handy, thanks.

While ```g:VM_user_operators``` sounds like a great thing, I don't understand why ```gu``` and ```gU``` cannot be supported natively.
Is it because they are using 2 letters instead of 1 like ```y```, ```d```, ```c``` etc?

I will take a look at ```vim-abolish```, but I think ```gu``` and ```gU``` are mainstream enough for it to add native support for it.
From your perspective I understand that this might be opening a Pandora box of a plethora of other commands. But maybe it's a good things?
What do you think?

Cheers,
Antoine 

Ps: I am never going back to vim-multiple-cursors, your plugin is really amazing!

**Comment by balta2ar** [comment]
> I am never going back to vim-multiple-cursors, your plugin is really amazing!

Now you understand my reasoning for advertising this plugin in vim-multiple-cursors issues about a year ago or earlier? The latter one is best depressed/archived with a banner offering a much better alternative -- it's only for the win of the users. Just my option though.

**Comment by mg979** [comment]
>  I don't understand why gu and gU cannot be supported natively.

Now they actually could, before I wasn't supporting custom operators (only the ones starting with c/d/y because there were already mappings for it). The only concern is too many mappings, but as long as they are the same as vim defaults it shouldn't be a problem.

> this might be opening a Pandora box of a plethora of other commands

Not really since I'm only going to support `gu/gU` and maybe later `g~/gw/gq`, the other `g` mappings aren't operators and shouldn't be mapped.

The point is that since you can do a normal command at cursors (`\\z` with default VM leader) some commands are maybe better not mapped (like `gq` since then I can't map `gqq` that one could expect to be working). It's too much work for stuff that probably won't be used, and for which there is an easy way already (`\\z` to run a normal command).

I'm going to support `gu/gU` for now, the rest maybe later.

> Now you understand my reasoning for advertising this plugin 

@balta2ar Thanks :)

**Comment by antoinemadec** [comment]
@mg979, agreed regarding gq. Thanks for gu!

@balta2ar , i still think that it would have been better for users to improve an existing plugin. It would have made things less confusing and this plugin would have a bigger following.

**Comment by mg979** [comment]
Test branch has been updated with some improvements related to this issue:

- built-in `gu/gU`: they work also in extend mode, with automatic reselection
- operators accept the repeated last character (eg `guu` makes the whole line lowercase)
- also user operators (in `g:VM_user_operators`) behave the same (`g~~` for example if you add it)

**Comment by antoinemadec** [comment]
@mg979 , could we reopen this?

There is a performance bug.
I was testing it today.

To reproduce it, just do:
  - ```10<C-down>```
  - press ```guu``` and ```gUU``` multiple times

At list on neovim, that will freeze the editor after some time.

**Comment by mg979** [comment]
Yes I see, I'll do some profiling to see what happens.

**Comment by antoinemadec** [comment]
Sounds good, i can try to create a test and add a timing mechanism if you
want?

That would be a useful addition to the regression tests.
What do you think?

**Comment by mg979** [comment]
It's a strange bug, profiling shows nothing (functions report normal times), even stranger is that if ou exit VM, then start it again, even motions are slow. It seems something more serious actually, it's not some VM bug. Maybe it has to do with change lists/undo stack.

**Comment by antoinemadec** [comment]
Maybe VM create too many mappings, or variables, or highlights etc?
Does this behavior also arises in Vim, or only Neovim?

**Comment by mg979** [comment]
Yes also in gVim and in terminal. VM does nothing different than usual, a couple more mappings can't be a problem.

**Comment by antoinemadec** [comment]
@mg979 that could be related to autocmd.
There is a perf bug in neovim with **CurshorHold** and **CursorHoldI** for instance: https://github.com/neovim/neovim/issues/12587

I guess creating too many auotcmd could lead to a behavior like this.
Slowdown seems exponential indeed.

I will try take a quick look at it this afternoon.

**Comment by mg979** [comment]
I opened a new issue for this because it's really obscure. From the issue you linked it seems different in vim/nvim, but here it is'n the case.

I tried to run the commands at cursors with `noautocmd lockmarks`, no change. So maybe it's autocmd related, maybe not.

**Comment by mg979** [comment]
@antoinemadec I found out the culprit. Not sure why it happens, but it does, I'll run tests then I update.
