### ISSUE TITLE
yy then p is not correctly supported

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#130]
**Describe the issue:**
It copies the lines but add a carriage return after the 1st character instead of before.

**Steps to reproduce**  

1. ```<C-Down>```
2. ```yy```
3. ```p```

-----

- **Operating System**:  Debian Testing
- **Vim Version**:  NVIM v0.5.0-606-g409a1dcdc
Build type: Release
- **commit SHA/branch**:  master

**Comment by mg979** [comment]
:h visual-multi-registers

Linewise pastes aren't (yet) supported, only if the linewise register it's an original vim register. This is because VM registers are lists of strings, and don't have a 'type' (linewise, block, etc). Still I want to support linewise pastes as an extra operation (in `devel` you can see I was working on that in last commit).

**Comment by mg979** [comment]
By the way if you want to do something like `yyp` you can already do it with `\\z`.

**Comment by antoinemadec** [comment]
Got it, thanks a lot!
