### ISSUE TITLE
Add cursors manually

### ISSUE THREAD

**Issue by midnio** [mg979/vim-visual-multi#15]
Actually, I use a lot this feature in Sublime Text & VS Code that makes you able to add a new cursor by pressing Alt-Click. I want this feature in this plugin like by pressing Alt-c and edit them by pressing Alt-d. I'll be very happy if you add this feature :smile:

**Comment by mg979** [comment]
It's [possible already](https://github.com/mg979/vim-visual-multi/wiki/Q.-Quick-start#using-the-mouse).
With keyboard, default mapping is `g<space>` to add single cursors. When adding single cursors you can add more of them in the same place (not possible otherwise), so that you can then press `i` and have multiple insertions of the same text.

Please report bugs if you find them, thanks :).

**Comment by midnio** [comment]
Thanks :) Then i remember you from mucomplete btw
