### ISSUE TITLE
Manually added cursors are resetting when press hjkl

### ISSUE THREAD

**Issue by midnio** [mg979/vim-visual-multi#16]
I want to use hjkl while I'm adding new cursors but I can't use them, a solution?

**Comment by mg979** [comment]
You can use arrows, `hjkl` are treated like motions. Or you can press `space` to temporarily disable mappings, then you can use`hjkl`, but to do anything you'd have to press `space` again, to reenable mappings.

**Comment by midnio** [comment]
This is my routine
```
g<Space>
l
g<Space>
l
```

And boom! there is 1 cursor again. Maybe test it yourself.

**Comment by midnio** [comment]
Ok, thanks, but if replace l with something else will be good.

**Comment by mg979** [comment]
> replace l with something else

What do you mean? The problem is that `hjkl` are used like all motions: they move cursors. Arrows don't do this. If you think about it, in other editors you can't move a single cursor without moving all other cursors. Here you can, but you must use arrows, because `hjkl` move all cursors. Or disable mappings with space. Does it make sense? It may look complicated, but I can't see simpler solutions.

**Comment by midnio** [comment]
You can replace hjkl with arrow keys maybe

**Comment by mg979** [comment]
But then in many other situations you would like to use `hjkl` to move all cursors. It can't just guess what you would like to do. I could add an option to invert behaviour (arrows to move cursors), but even that could be complicated because I use many times `hjkl` internally, to perform commands.

For now options are:

* `g<space>` and arrows
* `g<space>` and `space` to disable temporarily mappings, then you can use all motions
* use the mouse to add cursors (many times it's just easier)
