### ISSUE TITLE
[Question] Is It Possible to Select Non-contiguous Lines?

### ISSUE THREAD

**Issue by TheCedarPrince** [mg979/vim-visual-multi#163]
Hi all!

Thanks for this wonderful plugin! I use it everyday and find it a life saver!

I looked through the FAQ and Settings as well as the user guide but couldn't find anything related to the following question I am running into:

Say I have a list of lines that I want to yank items from from in a file (i.e. lines 1, 23, 42, 80). What I was hoping I could do was make individual cursors at the start of each of those lines and then edit the lines or yank from them accordingly. The closest I got with this was removing every n regions using the `\\R` operation.

Is it possible to select or make cursors arbitrarily throughout a given document? Thank you!

- **Operating System**: Fedora 32
- **Vim Version**: NVIM v0.4.4
- **commit SHA/branch**: 4c99296b8f29d8936de8c33d98f0acdafcdbd388 (most recent version as of this open issue)

**Comment by mg979** [comment]
If your mapping to add cursors is `\\\`, you could do something like:

    :normal 1gg\\\23gg\\\42gg\\\80gg\\\

Not sure what you want to achieve with that. If you yank lines/regions in VM they are stored as a `blockwise` register in vim, generally I use another plugin to convert a blockwise selection I get in VM to linewise, then I can paste it. Or you add some empty lines before pasting so that the blockwise paste actually fills the empty lines.

**Comment by mg979** [comment]
Anyway you can do this kind of things also with vim commands, for example in this case:

    :let @a = ''
    :normal! 1gg"Ayy23gg"Ayy42gg"Ayy80gg"Ayy

And you get an already linewise register to paste.
