### ISSUE TITLE
I just want to select a single letter under the cursor, then move it somewhere and do the same thing again.

### ISSUE THREAD

**Issue by arcanemachine** [mg979/vim-visual-multi#221]
I don't want to select lines, or groups of words, I just want to put the cursor somewhere in normal mode, place a marker there, move somewhere else, place another marker there, press `i`, and start inserting text.

How can I do this most basic of functions? The tutorial starts with more complex operations (lines), but I need to crawl before I can walk (dots).

I just need basic "insert some markers in arbitrary places and insert text in all those locations at the same time" functionality. If you tell me how to do this, I will make a pull request for the tutorial docs.

Thanks

**Comment by mg979** [comment]
`v<c-n>`? It works also with punctuation.

**Comment by mg979** [comment]
To move the cursor somewhere else, you must first disable mappings (default to toggle mappings is `<space>`), so you would:

1. select a letter with `v<c-n>`
2. press `<space>` to disable mappings
3. move somwhere else
4. press `<space>` again to reenable mappings
5. do whatever

Instead of toggling mappings, you can also move somewhere else directly with `/`, because it's not mapped by default.

**Comment by mg979** [comment]
Also, if you need to add cursors at very arbitrary positions, you can considering:

1. enabling mouse mappings (or map the plug yourself), so that you can use the mouse to place cursors
2. use `:VMSearch` that places cursors at patterns

**Comment by arcanemachine** [comment]
Thank you very much for the suggestions. I'm still trying to get things working but I appreciate the pointers.
