### ISSUE TITLE
Yggdroot/indentLine Disabled After Leaving VM/VM_after_auto not triggered

### ISSUE THREAD

**Issue by yarko3** [mg979/vim-visual-multi#25]
Hi, the [indentLine](https://github.com/Yggdroot/indentLine) plugin becomes disabled when leaving visual-multi mode.

I tried enabling it with the VM_after_auto() function but it doesn't seem to get triggered. Here's the VM_after_auto() I've written:

```
fun! VM_after_auto()
  echom "in VM_after_auto"
  IndentLinesEnable
endfun
```

I see nothing in `:messages` when exiting VM. I call the function directly (`:call VM_after_auto()`) and see the intended behavior. [My vimrc](https://github.com/yarko3/dotfiles/blob/master/vimrc).

**Comment by mg979** [comment]
That function is only called when running macros or normal/ex commands. I'll see what the problem can be. If you run `IndentLinesEnable` after exiting VM, does it work again?

**Comment by yarko3** [comment]
Yup.

**Comment by mg979** [comment]
Ok I'll check. Worse case I can add a hook for a function that is called when VM exits.

**Comment by yarko3** [comment]
Totally works!!! Thanks for the help.

**Comment by mg979** [comment]
Ok there's a problem with the current system and I'll have to change it, this is just a temporary fix.

**Comment by mg979** [comment]
I reworked a bit the fix because it could cause some problems. You can update again if you want.

**Comment by yarko3** [comment]
Still works; I see that the indent lines disappear while in VM now.

**Comment by mg979** [comment]
It was the same with the previous fix. They disappear when you make changes or start insert mode, because VM currently clears all buffer highlight matches. This isn't usually a problem but it is in this case.

I'm working on an alternative but I have to see if there are performance problems, because if I can't clear matches, it means I have to remove each match one by one when necessary, and this could cause slowdowns especially in insert mode, when all cursors have to be redrawn. But if it isn't too bad I'll make it work this way, so that it won't interfere with other plugins setting their own matches.

**Comment by mg979** [comment]
I reworked the system and now indentLine should work also in VM. This should fix the issue for good.

**Comment by yarko3** [comment]
Cool; this is still on the `test` branch?

**Comment by mg979** [comment]
Yes

**Comment by mg979** [comment]
The new system doesn't clear highlight matches, but it's not the default one, because it's about 20% slower than the default system (that clears all matches). It's automatically activated if using that plugin, though.

**Comment by yarko3** [comment]
Is the plan to move this into `master`?

**Comment by mg979** [comment]
I'll merge it into master maybe tomorrow.

**Comment by yarko3** [comment]
Thanks for helping out with this; it's working very well.

**Comment by mg979** [comment]
Good to know :)
