### ISSUE TITLE
Large amount of undo entries

### ISSUE THREAD

**Issue by sQVe** [mg979/vim-visual-multi#40]
_I'd like to first of all give you a huge **thank you** :pray: :clap: for this incredible plugin. I was a bit chocked when I first installed it, thinking I'd never get proper multi-cursor handling in Vim._

---

I'm seeing a big issue with this plugin related to undo entries. If I `touch` a file and add (via INSERT mode):
```
A
B
C
```
it has **1** undo entry. After this I set a _multi-cursor_ cursor at `B` with `g<Space>` and change that letter to `Z`. The document now has **533** undo entries. This is a pretty big issue as it kills the usefulness of undo.

**Comment by mg979** [comment]
Thanks, the plugin still needs improvements though :). About this issue, how do you verify the number of undo entries? It seems very strange to me. In this kind of operation (`g<space>rZ`) with a single cursor there shouldn't be any extra undo operation. You can press `u` and undo is performed normally (tested also with a minimal vimrc).

In other cases, I've been taking care to compress with `undojoin` many undo operations, for multiple changes that happen at different cursors, so that you can undo the whole operation at once. Especially if you enter insert mode.

In this case there is only one normal command that is issued, because there is a single cursor. How did you get that **533**?

**Comment by sQVe** [comment]
@mg979 I just reinstalled all my plugins and everything works fine and as expected. This issue was probably just isolated to my system due to updating issues. Closing.

**Comment by mg979** [comment]
All fine then. Still a bit curious about that 533 though.

**Comment by sQVe** [comment]
@mg979 With my setup it outputs the amount of entries in undo when pressing `u`. I'm running the latest version of `neovim`.

**Comment by mg979** [comment]
Understood, it's the same in vim. The important is that it fixed itself.

**Comment by sQVe** [comment]
I'm seeing this issue more and more now. I'm also experiencing crashes where `vim-visual-multi` is complaining about not finding an `ID`.

**Comment by mg979** [comment]
About the number of undone changes: I can reproduce it more or less but no idea what's causing it or if it's really harmful. With the same file:

* gvim 8.1 (Windows 10): it happens with 10 or more cursors, not with 9 or less
* vim/gvim 8.0 (Linux): 10 cursors are fine, but 11 are not

There are differences between environments, I can't see any real issue since undo works normally, but I'll investigate.

About the `ID`, which command causes this? Did you update to last master?

**Comment by sQVe** [comment]
@mg979 The amount of placed cursor makes no difference in my case. The undo history will still be spammed. The undo does not work normally for me. I need to press `u` for every undo entry...

Below is a small snippet from a `.jsx` file that I'm working with:
```jsx
<header className="overview-panel-header">
	<ResidenceInformationPartial residence={residence} />
	<hr />
</header>
```

If I place my cursor at `header`, press `<Ctrl-n>` three times and finally `c` to change I get the following error (just sometimes, around **25%** of the cases):

```
Error detected while processing function <SNR>262__doautocmd[7]..193[7]..<SNR>262__supercall[1]..187[3]..213[10]..215:
line    3:
E803: ID not found: 526
```

This error is spammed over and over so the only way to escape it is to restart `nvim`. The undo history is also populated with around `100` entries.

-----

System information:
```bash
% uname -sr && nvim --version | head -n 1
Linux 4.20.6-arch1-1-ARCH
NVIM v0.3.4
```

**Comment by mg979** [comment]
The only thing I can confirm is the abnormal undo changes that are registered, but I can undo them with a single keypress. I'll see what can cause them. I don't get those `ID` errors, when you get them please type:

    :scriptnames

and see what is that script n.`262` (or whatever it will be). There is possibly some script that is called on InsertEnter and interferes with VM. I can't reproduce the issue with the plugins I use, nor with a minimal vimrc. I should use `noautocmd` to solve this kind of issues, though.

To test it with a minimal vimrc, you could create a minimal-vimrc file:
```
if &compatible
  set nocompatible
endif

set packpath=
set runtimepath+=~/path/to/visual-multi
```

Then run:

    nvim -U NONE -u /path/to/minimal.vimrc

**Comment by sQVe** [comment]
@mg979 Awesome. I found the culprit that created the `ID` errors. `:scriptnames` pointed at `vim-highlightedyank` and uninstalling it removes that error! (https://github.com/machakann/vim-highlightedyank if you are interested).

It does not solve the undo entries though. There times where I have to press `u` 20-50 times or more to undo an simple replace with 3 cursors. Can you replicate the issue with my undo settings found here: https://github.com/sQVe/dotfiles/blob/kodama/config/nvim/options.vim#L73

I'll try to run a minimal-vimrc tonight and see if that solves the undo entries.

**Comment by sQVe** [comment]
@mg979 I've now gone through all my plugins an as soon as I remove `deoplete.nvim` undo works as expected. So `vim-visual-multi` together with `deoplete.nvim` is not playing together nicely. This is quite a big issue due to `deoplete.nvim` being a very popular plugin.

Tell me if I can help out debugging or give more information.

**Comment by mg979** [comment]
Ok, thanks for finding the cause. I don't use deoplete but I'd like to keep compatibility with it. At some point I tried it with VM and it was compatible, now I see that it's totally unusable with it (I could reproduce the undo bug). I'll see if there is an easy fix.

**Comment by mg979** [comment]
I pushed a fix in the test branch, but things with deoplete aren't perfect.

What changes if using deoplete, is that automatic completion is disabled, but you can press `Tab` to call the deoplete autocompletion popup. It's still a bit wonky because often you have to press `Tab` two times, but this is how deoplete works (probably a bug in it), I can see the function is called but the popup doesn't show up the first time.

That's the best I could do with deoplete for now, it just works very differently from other autocomplete plugins.

**Comment by sQVe** [comment]
@mg979 Awesome. I tried it out just now and getting:

```
Error detected while processing function vm#commands#ctrld[1]..<SNR>281_init[10]..vm#init_buffer[84]..vm#comp#init[10]..<SNR>295_deoplete:                                                                                                                                                   
line    7:
E121: Undefined variable: g:deoplete#disable_auto_complete
E15: Invalid expression: exists('g:loaded_deoplete') && deoplete#is_enabled() && !g:deoplete#disable_auto_complete
```
as soon as I try to place multiple cursors.

**Comment by mg979** [comment]
Sorry, it should be fixed now.

**Comment by sQVe** [comment]
@mg979 No worries. It works like a charm now. Well done :pray: :clap: :fist_oncoming: 

Closing.
