### ISSUE TITLE
Plugin messes up syntax highlighting in VISUAL mode

### ISSUE THREAD

**Issue by seletskiy** [mg979/vim-visual-multi#43]
When cursor moved in visual mode, syntax highlighting is messed up completely.

<p align="center">
<img src="https://user-images.githubusercontent.com/674812/52344790-b5e32280-2a2c-11e9-865b-ce210df0a2c0.gif" />
</p>

Steps:
* use `.vimrc.minimal` with contents below;
* run vim `vim -u .vimrc.minimal`;
* open file with some code;
* enter visual mode by pressing `v`;
* move cursor around;

Minimal reproducible configuration (with [vim-plug](https://github.com/junegunn/vim-plug)):
```
set nocompatible

call plug#begin('~/.vim/bundle')
Plug 'mg979/vim-visual-multi', {'branch': 'master'}
call plug#end()
```

First commit where problem appears is 23671f7 (identified with `git bisect`).

**Comment by mg979** [comment]
Vim version? Which terminal emulator? Does it happen even if you never start VM and just enter visual mode? I never saw this.

**Comment by seletskiy** [comment]
@mg979 
* vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 15 2019 00:11:27)
Included patches: 1-751
```
* terminal emulator: I've tried konsole and urxvt (both with and without tmux), reproducible in all cases;

It happens if I just enable VM in `.vimrc` without actually touching any of VM functions.

The problem is somehow linked to this autocommand:
```
:au plugin-visual-multi-start TextYankPost
--- Autocommands ---
plugin-visual-multi-start  TextYankPost
    *         call vm#operators#after_yank()
```

When I remove it, problem disappears.

**Comment by mg979** [comment]
Be sure to use last master because there have been some recent changes that could affect that. Atm I can't reproduce it, though. Testing in vim 8.0 (debian stretch) and nvim 0.4. I'll test in vim 8.1.

I tested it in xfce4-terminal and urxvt (unicode-256color), no problems there (I can't test in konsole).

Be also sure you don't have plugins in your runtimepath (`:set runtimepath?`), nor in your packpath or .vim/after directories.

For a really minimal vimrc in vim8, you could test with:

* put VM directory (or a symlink) in pack/test/opt/vm
* run `vim -Nu NONE -c "packadd vm"`
* open a file

**Comment by seletskiy** [comment]
Yeah, I've updated to master and that's how I found the problem.

I've also tried to run vim as you proposed using `packadd vm` to make sure that nothing else interfering with it, problem still persists.

Actually, it seems that it's a bug in vim itself, because problem is not reproducible with vim `8.0.1542`, but reproducible with vim `8.1.0022`. Possibly something goes wrong with `TextYankPost` autocommand.

**Comment by mg979** [comment]
It's a bit strange because that autocommand only calls a function that checks a bool and does nothing else most of the time. In nvim the same autocommand works without side effects. In vim 8.0 TextYankPost isn't used, so probably you don't see it for that reason (unless TextYankPost patch was already included in `8.0.1542`).

I tested it also in vim 8.1 (patches up to `1-707`), no problems in xfce4-terminal or urxvt. What colorscheme are you using in that minimal vimrc? Does it happen with syntax disabled? Because a minimal vimrc shouldn't enable syntax.

It could even depend on some terminal settings, but I don't know really.

**Comment by mg979** [comment]
Can you please try test branch? I replaced `##TextYankPost` with ``#TextYankPost` there, it should be the same but maybe not.

**Comment by seletskiy** [comment]
@mg979:

> What colorscheme are you using in that minimal vimrc?

Default one, I do not change anything, I just run `vim -Nu NONE -c 'packadd vm'`, then in vim I enable syntax by `:syn on` and open file with `:e a.go`.

> Does it happen with syntax disabled?

Nope, only with syntax on.

---

Actually, you know, I can just reproduce problem by adding `au TextYankPost * echo` with vanilla vim with zero configuration.

And I can't reproduce problem on same vim version on the remote server (over SSH).

I'm not sure what's going on, but it's certainly not this plugin problem, so feel free to close the issue.

Sorry for irrelevant task and thanks for the help!

**Comment by seletskiy** [comment]
@mg979:

OK, I've found the underlying cause: I have a program which synchronizes different X selection buffers (e.g. clipboard synchronizer), and when all following criteria are met then problem is reproducible:

* run `while :; do xclip -o | xclip -i -selection CLIPBOARD; done` as naïve form of clipboard synchronizer;
* open vim as `vim -Nu NONE -c "syn on"`;
* enable `TextYankPost` by `au TextYankPost * echo`;

**Comment by mg979** [comment]
Ok thanks for clarifying, this wasn't only hard to reproduce, but also to "produce".
