### ISSUE TITLE
How to change the registers used by actions?

### ISSUE THREAD

**Issue by sblask** [mg979/vim-visual-multi#46]
I have my vim setup to not yank implicitly by changing the register that certain action write to, see https://github.com/sblask/dotfiles/blob/master/.vimrc.d.symlink/keybindings_yank_paste.vim
So when I am on a word and press `ciw` I can paste something from my clipboard over it where by default I would paste the word I wanted to change (resulting in no change).

However, when I use vim-visual-multi my modifications don't work. Imagine when I am in a file and  want to replace  some occurrences of XYZ with the contents of my clipboard. I'd put my cursor on XYZ and press `ctrl-n` as often as necessary and then press `c` and then paste. That would replace XYZ with XYZ.

Is there a way to achieve the same kind of behaviour that I have without vim-visual-multi?

**Comment by mg979** [comment]
By default, `change` operations redirect the deleted content to the black hole, just as in your vimrc, so they should behave as you say.

It works for me if I do `yiW` outside VM, then select something and press `c<c-r>"`, to paste the yanked content. Also, instead of entering insert mode, you can just press `p` as in visual mode.

![Imgur](https://i.imgur.com/7oDqcid.gif)

I also tested it in a minimal vimrc and it works, so I don't know why it doesn't work for you.

**Comment by sblask** [comment]
And suddenly I cannot reproduce it anymore. I updated my plugins though, maybe it was just an old version that didn't work. Thanks for the clarifications!
I never tried `p` in VM. It works, but only for things that I copy inside vim, if I copy something from somewhere else it doesn't.

**Comment by mg979** [comment]
Maybe it has been temporarily broken in some older version, it happened.

About `p`, it works for me if I supply the register (`"+p`). VM uses the unnamed register by default and ignores clipboard settings because they've been cause for trouble. But `"+p` should work (in my environment it works at least).

**Comment by sblask** [comment]
Great, thanks!
