### ISSUE TITLE
[Request] Add "Move Up|Down"

### ISSUE THREAD

**Issue by jamespharvey20** [mg979/vim-visual-multi#62]
Since there's `Move Right|Left`, maybe there should also be a `Move Up|Down`.  There's the plugin [vim-move](https://github.com/matze/vim-move) which implements all 4, which I think is a decent idea showing how it could work.  (It is able to correct for indentation when going up/down.)  As I feared, as an example, when I've used vim-visual-multi to select a 3x3 grid of characters, vim-move doesn't see a true selection, so it's unable to move anything.  To move up/down, that forces having multiple ways to select text depending on direction, and using a different plugin depending on direction.

**Comment by mg979** [comment]
I don't think it makes much sense moving multiple selections up and down. Right now I'm more focused on fixing what bug may be left, rather than implementing even more funny stuff.

Anyway I remember you can [run normal commands at cursors](https://github.com/mg979/vim-visual-multi/wiki/Commands-at-cursors#normal-commands), it's recursive so you can run a `<Plug>something` or a normal mapping from a plugin, or you can run an [ex command](https://github.com/mg979/vim-visual-multi/wiki/Commands-at-cursors#ex-commands), so you can achieve many things without having some built-in functionality.
