### ISSUE TITLE
Setting custom "VM_highlight_matches" causes unhandled exception

### ISSUE THREAD

**Issue by jamespharvey20** [mg979/vim-visual-multi#66]
If I put this in my vimrc:

````
let g:VM_highlight_matches="Pmenu"
````

or
````
hi hi_matches ctermfg=16 ctermbg=208
let g:VM_highlight_matches="hi_matches"
````

Then when pressing `<C-n>`, it gives this error:

````
Error detected while processing function vm#commands#ctrln[1]..<SNR>153_init:
line   11:
E605: Exception not caught: VM cannot start, unhandled exception.
````

Because a literal reading of https://github.com/mg979/vim-visual-multi/wiki/Highlight-colors#matches-highlight indicates this, I tried this also:

````
let g:VM_highlight_matches="hi ctermfg=16 ctermbg=208"
````

But, that doesn't do anything.

I can successfully use this:
````
let g:VM_highlight_matches="red"
````

I can also successfully set `g:VM_Selection_hl`, `g:VM_Mono_Cursor_hl`, `g:VM_Ins_Mode_hl`, and `g:VM_Normal_Cursor_hl`, i.e.:

````
hi VM_Normal_Cursor_hl ctermfg=53 ctermbg=207
let g:VM_Normal_Cursor_hl="VM_Normal_Cursor_hl"
````

---

As a bonus bug, this can't be changed once it's been used:

````
(select all without g:VM_highlight_matches overridden, and it underlines)
:let g:VM_highlight_matches='red'
(escape to go back to normal mode)
(select all again, still underline)
````

vs restarting vim

````
:let g:VM_highlight_matches='red'
(select all, now it's red)
````

This "bonus" bug I don't really care about, just mentioning since I ran into it trying to speed up trying to figure out how to set `VM_highlight_matches`.

**Comment by mg979** [comment]
Sorry, there was a mistake in the wiki (corrected now), if you want to give
a full command, you should write it like that:

```
let g:VM_highlight_matches = 'hi! link Search Pmenu'
```

or to give new colors:
```
let g:VM_highlight_matches = 'hi Search guifg=#xxxxxx' etc
```

It works if I write:
```
let g:VM_highlight_matches = 'hi! link Search IncSearch'
```

but if you change it after vim has started (from the command line), you should
also reload the VM theme (`VMTheme ...`) because the highlight is initialized
with the theme.

You could actually set:
```
let g:Vm.Search = 'hi! link Search IncSearch'
```

and you wouldn't need to reload the theme. I'll make it so that you don't need to reload the theme even with the 'normal' way.

**Comment by mg979** [comment]
It should work now, thanks for reporting, you can reopen if still having problems.
