### ISSUE TITLE
How do I change each selection differently?

### ISSUE THREAD

**Issue by Avi-D-coder** [mg979/vim-visual-multi#68]
Given

`Float Float` 
<kbd>C-n</kbd><kbd>C-n</kbd> Selects both, I want to change the first to `x` and the second to `y`.
`x y`

Is there a way to handle each selection manually.

**Comment by mg979** [comment]
It depends on what you want to do, maybe you can give a full example?

I wanted to implement selection groups at some point (so that you can switch group and do different things with each) but not sure if it's really useful. Right now there is no 'easy' way to do something like that.

If the text is different, you can transform it (`:help vm-transform`), the expression would be like
`%t == some_text ? x : y` (region text is transformed to x if the original text is some_text, or to y)

If they're different numbers you can compare them
`%t > some_number ? x : y`

If you have multiple regions that follow some patterns (like you want to change in some different way the regions that come before a certain column), you can also use region attributes in the expression
`r.a < col_num ? x : y` (r.a is the starting column of the region)

Otherwise, if you have a register of type `block` (like `C-V`) you can paste it, and every 'cell' (line) of the block will go in one region.

You could also use some simple script to generate a register of type block with the text you need, then paste it, for example you open a new buffer, `:setf vim`, you write something like

```vim
let text = []

for i in range(10)
  if i % 2
    call add(text, "string for even regions")
  else
    call add(text, "string for odd regions")
  endif
endfor

call setreg('"', join(text, "\n"), 'b')
```

Then you do `:%y | @"`, you create the selections and paste the text.

**Comment by Avi-D-coder** [comment]
> I wanted to implement selection groups at some point (so that you can switch group and do different things with each) but not sure if it's really useful.

I think this is what I was looking for. I saw a kak example of it being used somewhere. Thanks

**Comment by mg979** [comment]
Ok, but in case I wanted to implement something like that, what would be the workflow? I'm not sure how somebody would use it in practice, so I don't know what would be a good way to do it.

**Comment by Avi-D-coder** [comment]
There are often instances where I am working with many selections that need to end up the same, except a few details. The current situation is I make my multiline edits and then manually go to each place I edited to finish the edits.

**Comment by mg979** [comment]
Understood. I think some sort of sequential region editing would be better for these cases.  A way to edit regions one by one, that is.

For example, start sequential editing, entering insert mode at currently selected region, then move through regions with `ctrl-n`/`ctrl-p` in insert mode.

Also you can check `:help vm-smart-case-change`, but it's for limited cases.

**Comment by Avi-D-coder** [comment]
I would find it more useful if I could move thru cursors in normal mode. That way I could use all the normal mode bindings and move an individual cursor then switch back to multi cursor mode.

**Comment by mg979** [comment]
You can already move thru cursors with { and }. But thinking about it, to edit things one by one, searching the pattern with / and using n/N and maybe using `gnA` if you need to make edits at the end of the match, would barely make any difference. It's probably the kind of things that can be better achieved with normal vim stuff or a one-shot macro if you need a shortcut like gnA or similar. Or not?

**Comment by Avi-D-coder** [comment]
<kbd>{</kbd><kbd>}</kbd> move thru cursors, but don't allow me to apply commands to just a single cursor then switch back to all cursors. I was unable to get `/` or `gna` achieve the desired result.

The video of [kakoune-snippets](https://github.com/occivink/kakoune-snippets) shows just how use full this feature can be.

**Comment by mg979** [comment]
Ok, so I can do something like:

`gi`: enter insert mode by editing sequentially at cursors positions, `Esc` stops insert mode and brings you to next cursor.

and:

`gI`: enter insert mode by editing sequentially at cursors positions, `Esc` stops insert mode, brings you to next cursor and enters insert mode again. If you want to skip some cursor you keep pressing `Esc`. It stops when all cursors are processed, or with `<C-]>`.

Or too complex?

**Comment by Avi-D-coder** [comment]
I think this is the closest to what I'm looking for [kakoune-phantom-selection](https://github.com/occivink/kakoune-phantom-selection).

The sequential behavior and insert is not always what I'm looking for.

I think more along the lines of `gi` your put in standard visual mode with the selection under your main cursor, except `esc` is mapped to restoring muli mode.

So the workflow could be <kbd>C-n</kbd><kbd>C-n</kbd><kbd>gi</kbd> Visual mode, only second selection present<kbd>c</kbd> Insert mode, edit selection <kbd>Esc</kbd>  normal mode cursor at end of change<kbd>w</kbd><kbd>Esc</kbd> Multi mode restored still on second selection which is now just a cursor. If  <kbd>w</kbd><kbd>v</kbd><kbd>w</kbd> had been pressed in normal mode then <kbd>Esc</kbd> the second cursor would now have selected the word after the edit.

**Comment by mg979** [comment]
@Avi-D-coder I've worked on this feature, it's in the test branch if you want to try it. It's called *single region mode* (`:help vm-single-mode`). It already existed for motions but now it supports insert mode too.

Workflow would be: first, enable single region mode (default `\\<CR>`). Then:

- move to cursor with `[` or `]` in normal mode, enter insert mode with `i/a`, make change, `esc`, move to another one, make change, etc
- you can use `Tab`/`S-Tab` in insert mode to quickly go to next cursor (`C-n` must be used to select autocompletion item)

Note that if you start from extend mode and press `c` while in single region mode, it still deletes everything, but then you can switch cursors with `Tab`. Or you can press `i` or `a`, content is not deleted and you add text, rather than replacing.

![Imgur](https://i.imgur.com/s8ce3KK.gif)

**Comment by Avi-D-coder** [comment]
Thank you this is very useful

**Comment by mg979** [comment]
Now in master.

**Comment by Avi-D-coder** [comment]
The other part of this issue is normal mode operations on a single cursor.

**Comment by mg979** [comment]
I'll see if there's an easy way to do it.

By the way there are tons of alternatives for this kind of things, for example `n/N` with plugins that allow `*` for visual selection (I use [thinca/vim-visualstar](https://github.com/thinca/vim-visualstar/blob/master/plugin/visualstar.vim)).
