### ISSUE TITLE
C-d alternative

### ISSUE THREAD

**Issue by daniele-orlando** [mg979/vim-visual-multi#8]
`C-d` is mapped by default to the internal VIM _"Scroll window downwards"_ and VM overwrites it.

I know that it can be prevented with `let g:VM_sublime_mappings = 0`, but it disables all other useful mappings too.

Why VM is not using in normal mode the more agnostic `C-n` like [vim-multiple-cursors](https://github.com/terryma/vim-multiple-cursors) does, optionally allowing to opt in for the Sublime mapping only if configured with a specific variable?

**Comment by mg979** [comment]
Reasons are:

* `C-d` is the default key for word selection in other editors with multiple selections
* in vim `C-d` and `C-f` do similar things, I don't think you need more than one. I use `C-f` but remap it as `<C-d>z.`, because `C-d` is more useful.
* `C-n` isn't a good mapping imo, most people would remap it to `C-d` anyway I think. Especially those who aren't born vimmers and just want to jump in.

To find mappings that are good for everybody is difficult. I'll provide a way to define mappings from the ground up, if one so desires.

**Comment by mg979** [comment]
Now it's possible to customize mappings, and `C-n` is default for `select word under cursor`, unless `g:VM_sublime_mappings` is enabled.

Read the [wiki](https://github.com/mg979/vim-visual-multi/wiki/M.-Mappings#options-and-customization) for infos.

**Comment by mg979** [comment]
In the test branch, not on master.

**Comment by daniele-orlando** [comment]
I'm reading from the Wiki and it seams you have done a great job about customizing VM. 
ASAP I'll try the test branch.
