### ISSUE TITLE
Align does not align but replace rest of line with contents of register 0

### ISSUE THREAD

**Issue by sblask** [mg979/vim-visual-multi#95]
Consider following file and register 0 being set to foobar using `:let @0='foobar'`:

```
  align-me
      aligne-me
   align-me
```
when I set the cursors  onto `align-me` and then hit leader-a I get the following:
```
      foobar
      foobar
      foobar
```
I disected my config and it's because of this line:
```
nnoremap D  "_D
```
I want to keep the line because I don't like vims default behaviour of overriding the 0 register. Is there any way of getting align to work properly with this line? Note, I have other similar remaps as well(see https://github.com/sblask/dotfiles/blob/master/dotfiles_shared/.vimrc.d.symlink/keybindings_yank_paste.vim) that might cause problems elsewhere. I haven't looked at the code, but it would probably a good idea to explicitly provide a register when doing vim actions.

**Comment by mg979** [comment]
Thanks for reporting, is it fixed now?

**Comment by mg979** [comment]
Just to clarify: even if I use an explicit register, it won't fix the issue, because if you do:

    nnoremap d "_d

then doing

    normal "adE

will be interpreted as

    normal "a"_dE

You can verify it by trying to use any explicit register with your mapping, it will never be used.

The only solution here would be to use a non-recursive mapping, but since I use a lot [targets.vim](https://github.com/wellle/targets.vim) I don't want it to be the only option. I'll probably make non-recursive commands the default, just to be on the safe side.

**Comment by mg979** [comment]
In current master there's a new option you can set

    let g:VM_recursive_operations_at_cursors = 0

Default is 1 for now because it would break previous behaviour, also it seems to be important in your case but I'm not sure about others.

The issue with the alignment command was different though, that was fixed and it doesn't need this option.

**Comment by sblask** [comment]
Cool, works. Thanks so much!
