### ISSUE TITLE
`_` doesn't work as expected

### ISSUE THREAD

**Issue by pokey** [mg979/vim-visual-multi#96]
If I create multiple cursors using "Add cursor below", then when I press `_`, it only moves one cursor to the first non-whitespace character of the line, whereas I'd expect it to move all cursors.

Great plugin tho!  Performance is great

**Comment by mg979** [comment]
`_` isn't mapped by default. You can map it like this:

    let g:VM_custom_noremaps = { '_': '_' }

this will create a command that will work on all cursors inside VM. For example I have:

    let g:VM_custom_noremaps = {'==': '==', '<<': '<<', '>>': '>>'}

so that I can reindent.

The main limitation of this system (compared to built-in motions) is that these commands only work in cursor mode, not extend mode (they force cursor mode).

By the way '^' is similar and is supported as motion. I could support also '_', it's not a big stretch, I'd just need to add it to the motions characters, just not sure if it's a good idea to support every single motion, because they are a lot, it means more default mappings and potentially more conflicts. For example `_` is rather common as prefix for buffer mappings, so I'd prefer to avoid it.

**Comment by pokey** [comment]
Ah right ok was wondering about `<<` as well.  Those defaults sound reasonable to me.  Thanks!
