### ISSUE TITLE
Compatibility with Ultisnip

### ISSUE THREAD

**Issue by eyalk5** [mg979/vim-visual-multi#97]
Hi,
visual-multi is incompatible with Ultisnip. It messes up the text. 

To reproduce, install Ultisnip and add to tex.snippets  (Ultisnip folder on vim) the lines: 

```
snippet @c "mathcal" iA
\mathcal{${1:${VISUAL}}}$0
endsnippet
```

The process is the following:
1. I select some regions using \<ctrl-N\>
2. I press c to change
3. I write @c to expand Ultisnip's mathcal snippet
4. I continue to write blabla.  

Part 3 is done correctly on all regions. but `blabla` is only written correctly in the current region. Other regions are messed up.
It happens in other snippets as well. 

I am with the latest visual-multi and neovim 0.5 on nvim-qt. 
Solving this would be appreciated.

Thanks.

**Comment by mg979** [comment]
`:help vm-insert-mode`

It's stated in the documentation, it won't work with snippets. It works with abbreviations if they don't try to do fancy stuff with arrow keys, beacuse VM only tracks changes _before_ cursor position, not _after_ it, that would be much too complex for me. For Ultisnips, situation is worse because VM and Ultisnips would fight over autocommands and line changes, so this is simply impossible.

Try to use abbreviations, I don't think there's an editor out there that works with snippets in multiple cursor mode, having abbreviations is already as far as you can go.

You can also use macros: record a macro, insert a snippet, then replay the macro (this should work also with VM `\\@`).

**Comment by eyalk5** [comment]
I agree that it is hard. Snippets are irreplaceable with abbrv. Not high chances but I might write a PR for Ultisnip specifically.

**Comment by mg979** [comment]
I don't want to discourage you but I think you would be wasting your time.

- in most snippets, the cursor position is not placed at the end of the text, but somewhere in the middle, VM cannot know where, it would be too unpredictable to guess, not to mention placeholders jumping that would require an implementation of its own.

- Ultisnips uses autocommands as VM does, and they can't work together because they would step on each other toes trying to modifying the same line

It would be easier to make a simpler VM-specific snippet engine, rather than ensuring compatibility with Ultisnips that's a complex plugin on its own. But even that would not be trivial. I used snippets with macros sometimes and it worked well, so for me this would be a complex solution to a problem that has already a solution of some kind, I think it's not worth it. And for simple stuff abbreviations work better than you think.
